config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  resources :materials
  resources :products do
    put :favorite, on: :member
  end
  resources :contacts, only: [:new, :create]

  resources :categories
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
  get 'home/favoritos'
  get 'home/compra'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end

end

app/views/home/carrito.html.erb
<% if !current_user %>
<div class="carrit">
  <h2>Registrate para empezar a comprar!</h2><br><br>
    <%= link_to "Registrarse Gratis", new_user_registration_path, class:"carro" %>
</div>

<% elsif current_user.favorites.length == 0 %>
<div class="carrit">
  <h2>Todavia no has comprado nada</h2><br><br>
    <%= link_to "Buscar productos", products_path, class:"carro" %>
</div>

<% else %>
    <ul class="car">
      <% @product = current_user.favorites %>
      <% @product.each do |f| %>
      <li>
        <%= link_to f  do %>
        <%= image_tag f.photo.url(:medium), size:"100x50" %>
        <% end %>
        <h3>$<%= f.price.round %></h3>
        <%= link_to "Quitar", favorite_product_path(f, type: "unfavorite"), method: :put %>
      </li>
      <% end %>
      <div class="total">
        <h5>Total a pagar:</h5><h3>$<%= @product.sum(:price) %></h3>
      </div>
    </ul>

<% end %>

app/views/home/compra.html.erb
<div class="container">
  <div class="row" style="text-align:center">
      <div class="col-lg-9" style="margin-left:auto; margin-right:auto; width:auto; margin-top:auto; padding:10%;">
    <p class="gracias"><strong>Gracias <%= current_user.name %> por comprar con nosotros, pronto nos estaremos comunicando para arreglar el envio.</strong><br>
      En caso de que no nos comuniquemos en las proximas 24hs comunicarse a:<br>
    <strong>horneroceramica@gmail.com</strong> o al <strong>2944661505</strong></p><br>
    <%= link_to "Seguir Comprando", root_path, class:"carro" %>
    </div>
  </div>
</div>

app/views/home/favoritos.html.erb
<% if !current_user %>
<div class="carrit">
  <h2>Registrate para empezar a comprar!</h2><br><br>
    <%= link_to "Registrarse Gratis", new_user_registration_path, class:"carro" %>
</div>

<% elsif current_user.favorites.length == 0 %>
<div class="carrit">
  <h2>Todavia no has comprado nada</h2><br><br>
    <%= link_to "Buscar productos", products_path, class:"carro" %>
</div>

<% else %>
    <ul class="car">
      <% @product = current_user.favorites %>
      <% @product.each do |f| %>
      <li>
        <%= link_to f  do %>
        <%= image_tag f.photo.url(:medium), size:"100x50" %>
        <% end %>
        <h3>$<%= f.price.round %></h3>
        <%= link_to "Quitar", favorite_product_path(f, type: "unfavorite"), method: :put %>
      </li>
      <% end %>
      <div class="total">
        <h5>Total a pagar:</h5><h3>$<%= @product.sum(:price) %></h3>
      </div>
      <%=link_to "Checkout", new_transaction_path, class: "btn" %>
    </ul>

<% end %>

app/views/home/index.html.erb
Hola
 <%= link_to "hola", new_user_registration_path %>