config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  resources :materials
  resources :products do
    put :favorite, on: :member
  end
  resources :contacts, only: [:new, :create]

  resources :categories
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
  get 'home/favoritos'
  get 'home/compra'
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user, required: true
  belongs_to :category, required: true
  belongs_to :material

  def self.search(search)
    where("name LIKE ? OR description LIKE ? OR name LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%", "%#{search.capitalize}%", "%#{search.capitalize}%")

  end
  #carts
  has_many :favorite_products # just the 'relationships'
  has_many :favorited_by, through: :favorite_products, source: :user

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_attached_file :photo1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  has_attached_file :photo1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo1, content_type: /\Aimage\/.*\z/

  has_attached_file :photo2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  has_attached_file :photo2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo2, content_type: /\Aimage\/.*\z/


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]

  # GET /products
  # GET /products.json
  def index
    if params[:search]
       @products = Product.search(params[:search])
    else
      @products = Product.left_joins(:favorite_products).group(:id).order("COUNT(products.user_id) DESC").uniq
    end
  end

  # GET /products/1
  # Add and remove favorite recipes
  # for current_user
  def favorite
    type = params[:type]
    if type == ""
      current_user.favorites << @product

    elsif type == "unfavorite"
      current_user.favorites.delete(@product)
    end
  end

  # GET /products/1
# GET /products/1.json
def show
end

# GET /products/new
def new
  @product = current_user.products.build
end

# GET /products/1/edit
def edit
end

# POST /products
# POST /products.json
def create
  @product = current_user.products.build(product_params)

  respond_to do |format|
    if @product.save
      format.html { redirect_to @product, notice: 'Product was successfully created.' }
      format.json { render :show, status: :created, location: @product }
    else
      format.html { render :new }
      format.json { render json: @product.errors, status: :unprocessable_entity }
    end
  end
end

# PATCH/PUT /products/1
# PATCH/PUT /products/1.json
def update
  respond_to do |format|
    if @product.update(product_params)
      format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      format.json { render :show, status: :ok, location: @product }
    else
      format.html { render :edit }
      format.json { render json: @product.errors, status: :unprocessable_entity }
    end
  end
end

# DELETE /products/1
# DELETE /products/1.json
def destroy
  @product.destroy
  respond_to do |format|
    format.html { redirect_to products_path, notice: 'Product was successfully destroyed.' }
    format.json { head :no_content }
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :user_id, :category_id, :photo, :photo1, :photo2, :material_id, :link)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<form enctype="multipart/form-data" action="/products" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">

  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>


  <div class="field">
    <label for="product_name">Nombre</label>
    <input type="text" name="product[name]" id="product_name">
  </div>


    <select class="form-control" name="product[category_id]" id="product_category_id">
      <option value="">Elegir categoria</option>
      <option value="1">Vajillas</option>
      <option value="2">"Macetas"</option>
      <option value="3">"Floreros"</option>
      <option value="4">"Candelabros"</option></select>

      <select class="form-control" name="product[material_id]" id="product_material_id">
        <option value="">Elegir material</option>
        <option value="1">Ceramica</option></select>

  <div class="field">
    <label for="product_description">Descripcion</label>
    <textarea name="product[description]" id="product_description"></textarea>
  </div>

  <div class="field">
    <label for="product_price">Precio</label>
    <input type="text" name="product[price]" id="product_price">
  </div>

  <div class="field">
    <label for="product_link">Link de Pago</label>
    <input type="text" name="product[link]" id="product_link">
  </div>


  <div class="field">
    <label for="product_photo">Foto Principal</label>
    <input type="file" name="product[photo]" id="product_photo">
  </div>

  <div class="field">
    <label for="product_photo1">Foto Secundaria 1</label>
    <input type="file" name="product[photo1]" id="product_photo1">
  </div>

  <div class="field">
    <label for="product_photo2">Foto secundaria 2</label>
    <input type="file" name="product[photo2]" id="product_photo2">
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Create Product" data-disable-with="Create Product">
  </div>
</form>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= form_for @product do |f| %>

<%= f.text_field :name %><br>

<%= f.text_field :link %><br>

<%= f.number_field :price %> <br>

<%= f.text_area :description %>

<%= f.file_field :photo1 %>

<%= f.file_field :photo2 %>

<%= f.submit "Editar" %>

<% end %>

app/views/products/index.html.erb
<div class="container">

  <div class="row">
    <!-- /.col-lg-3 -->

    <div class="col-lg-9" style="margin-left:auto; margin-right:auto">

            <form id="search-form" action="/products" accept-charset="UTF-8" method="get" class="form-inline my-2 my-lg-0" style="padding: 20px; width: fit-content; margin-left:auto; margin-right:auto;">
          <input name="utf8" type="hidden" value="✓">
          <input type="text" name="search" id="search" placeholder="Buscar un producto" class="form-control mr-sm-2" style="text-align:center">
          </form>


      <div class="row">

        <% @products.each do |f| %>
        <div class="col-lg-4 col-md-6 mb-4 cd">
          <%= link_to(f) do %>
          <div class="card1">
              <% if f.photo.present? %>
                <%= image_tag f.photo.url(:medium), style:"margin-left:auto; margin-right:auto", class:"card-img-top", alt:"" %>
              <% end %>
            <div class="card-body">
              <h4 class="card-title">
                <%= f.name %>
              </h4>
              <h5 class="card-price">$<%= f.price.round%></h5>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
      </div>
      </div>
      </div>

app/views/products/new.html.erb
<% if current_user.admin %>
<h1>Producto Nuevo</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

<% end %>

app/views/products/show.html.erb
<% content_for :titulo, @product.name%>
<% meta_tag :description, @product.description %>
<% meta_tag :keywords, @product.name.split.join(',') %>


<div class="container">

  <div class="row">

    <div class="col-lg-9" style="margin-left:auto; margin-right:auto; width:auto">

      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel" style="width: fit-content; margin-left:auto; margin-right:auto" >
        <div class="carousel-inner" role="listbox" style="margin-left:auto; margin-right:auto; width:fit-content">
          <div class="carousel-item active">
            <%= image_tag @product.photo.url(:medium), class:"d-block" , style:"height:300px;" %>
          </div>

          <div class="carousel-item">
            <% if @product.photo1.present? %>
              <%= image_tag @product.photo1.url(:medium),class:"d-block" , style:"height:300px;"%>

            <!-- <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide"> -->
          </div>
            <% end %>

            <div class="carousel-item">
              <% if @product.photo2.present? %>
                <%= image_tag @product.photo2.url(:medium),class:"d-block " , style:"height:300px;"%>

              <!-- <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide"> -->
            </div>
              <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">
        <h1 class="titulo"><%= @product.name %></h1><br>
      </div>
      <div class="row">
        <h1 class="precio">$<%= @product.price.round %></h1>
      </div>
      <div class="row">
        <% if current_user %>
        <%= link_to "Comprar Ya", "#{@product.link}", class:"carro" %>
        <% else %>
        <%= link_to "Comprar Ya", new_user_registration_path, class:"carro", onclick:"test" %>
        <% end %>
      </div>

    <% if current_user %>
    <% if current_user.admin? %>
    <li class="user"><h6><%= link_to "Eliminar",product_path(@product), :method => 'delete', data: {confirm: 'Seguro que desea eliminar el producto'} %>
       &nbsp&nbsp&nbsp <%= link_to "Editar", edit_product_path(@product) %></h6></li>
    <% end %>
    <% end %>
      <div class="row">
        <p class="descripcion"><%= @product.description %><br>Esta realizada con: <strong><%= @product.material.name %></strong></p>
      </div>
      </div>

    </div>

  </div>

</div>