config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  resources :materials
  resources :products do
    put :favorite, on: :member
  end
  resources :contacts, only: [:new, :create]

  resources :categories
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
  get 'home/favoritos'
  get 'home/compra'
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">

    HorneroCeramica © 2019 Todos los derechos Reservados
  </div>

  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_nav.html.erb
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar" style="position:sticky;top: 0; z-index:100; background-color:#585a61">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
      <% @cart = current_user.favorites.length %>
      <% end %>
      <li class="nav-item">
        <%= link_to "/", class:"navbar-brand" do %>
        <img src=" https://s3-sa-east-1.amazonaws.com/hornero-recetas/IconoO.png" width="40" height="40" alt="">
        <% end %>
      </li>
      <% if !current_user %>
      <li class="nav-item">
        <%= link_to "Comprar", products_path, class:"nav-link" %>
      </li>
      <% end %>

      <% if current_user && current_user.admin? %>
      <li class="nav-item">
        <%= link_to "Producto Nuevo", new_product_path, class:"nav-link" %>
      </li>
      <% end %>

      <% if current_user %>
      <li class="nav-item">
        <%= link_to "Productos", products_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Salir", destroy_user_session_path, class:"nav-link", :method => 'delete' %>
      </li>
      <% end %>
    </ul>
</header>

app/views/layouts/_nav2.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" width="10" height="10" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% Category.all.each do |c| %>
      <li class="nav-item">
        <%= link_to c.name, c, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
  <%= if content_for?(:titulo) then yield(:titulo) + ' | ' end %>
  Hornero Ceramicas
</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='description'
     content='<%= yield_meta_tag(:description, 'Productos de Ceramica desde Bariloche') %>' />
   <meta name='keywords'
     content='<%= yield_meta_tag(:keywords, 'ceramica,ceramicas,hornero,taller,bariloche') %>' />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/nav2' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>